### ISSUE TITLE
deb-ostree-builder needs github key on the master branch

### ISSUE THREAD

**Issue by jeremiah** [dbnicholson/deb-ostree-builder#2]
While trying to use deb-ostree-builder I get the following error;

git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Traceback (most recent call last):
  File "./deb-ostree-builder", line 102, in <module>
    subprocess.check_call(['git', 'fetch', 'origin'])
  File "/usr/lib/python3.7/subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['git', 'fetch', 'origin']' returned non-zero exit status 128.

I've configured the default.ini, but there is no mention of a git repo. What is the program looking for at GitHub?

**Comment by dbnicholson** [comment]
Yeesh, I forgot about that. It's trying to update itself. That's based on something our internal Endless builder does. You should try the `simple-builder` branch (which I should just merge to master what's here is unmaintained).

**Comment by jeremiah** [comment]
I thought it was doing something like that. I ran it in strace and it looked like it was checking out itself to a build directory. :-) I couldn't see where to add credentials. I'll use simple-builder branch.
